// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCytaS3jgoxr0xJMJqnQrH4bm3TbCQhm-4',
    appId: '1:544398683136:web:0e825b9f7f31cf5bf97ce5',
    messagingSenderId: '544398683136',
    projectId: 'instagram-clone-app-1e04b',
    authDomain: 'instagram-clone-app-1e04b.firebaseapp.com',
    storageBucket: 'instagram-clone-app-1e04b.appspot.com',
    measurementId: 'G-C2XYLQ3908',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj2a4mBvV2wAcUXZJLXlbX7lhOqfXCvc0',
    appId: '1:544398683136:android:2b9d81bbc9db5bc4f97ce5',
    messagingSenderId: '544398683136',
    projectId: 'instagram-clone-app-1e04b',
    storageBucket: 'instagram-clone-app-1e04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjX1nSC-DwxTlW32zuhPfiWWO0f8dtOPE',
    appId: '1:544398683136:ios:9e13a313ac5fdd6bf97ce5',
    messagingSenderId: '544398683136',
    projectId: 'instagram-clone-app-1e04b',
    storageBucket: 'instagram-clone-app-1e04b.appspot.com',
    iosClientId: '544398683136-q2va7ov66t89mos1389q5p226fkpdihv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjX1nSC-DwxTlW32zuhPfiWWO0f8dtOPE',
    appId: '1:544398683136:ios:c93a0526eb3d3712f97ce5',
    messagingSenderId: '544398683136',
    projectId: 'instagram-clone-app-1e04b',
    storageBucket: 'instagram-clone-app-1e04b.appspot.com',
    iosClientId: '544398683136-st3akdr1karhl1iladcbto0khnh6jrut.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
